# fly.toml app configuration file generated for umigame-bot on 2026-05-02T21:43:01+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'umigame-bot'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
